[project]
name = "newscast-generator-lambda"
version = "1.0.0"
description = "AWS Lambda function for newscast generation with FFmpeg audio processing"
requires-python = ">=3.13"
dependencies = [
    "typer>=0.12.0",
    "rich>=13.0.0",
]

[project.optional-dependencies]
dev = [
    "boto3>=1.35.0",
    "pytest>=8.0.0",
    "pytest-cov>=4.1.0",
]

[project.scripts]
test-lambda = "test_lambda:app"

[tool.uv]
dev-dependencies = [
    "boto3>=1.35.0",
    "pytest>=8.0.0",
    "pytest-cov>=4.1.0",
]