[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ai-newscast-crawler"
version = "1.0.0"
description = "BigKinds news crawler for AI News Cast"
authors = [
    {name = "AI News Cast Team"},
]
dependencies = [
    "requests>=2.31.0",
    "lxml>=4.9.0",
    "click>=8.1.0",
    "pydantic>=2.5.0",
    "python-dateutil>=2.8.0",
]
requires-python = ">=3.11"

[tool.uv]
dev-dependencies = [
    "pytest>=7.4.0",
    "pytest-asyncio>=0.21.0",
    "black>=23.0.0",
    "isort>=5.12.0",
    "mypy>=1.5.0",
    "ruff>=0.1.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "pytest-asyncio>=0.21.0",
    "black>=23.0.0",
    "isort>=5.12.0",
    "mypy>=1.5.0",
    "ruff>=0.1.0",
]

[project.scripts]
bigkinds-crawler = "bigkinds_crawler.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["src/bigkinds_crawler"]

[tool.hatch.build.targets.sdist]
include = [
    "/src",
    "/pyproject.toml",
    "/README.md",
]

[tool.black]
line-length = 88
target-version = ['py311']

[tool.isort]
profile = "black"
line_length = 88

[tool.mypy]
python_version = "3.11"
strict = true
warn_return_any = true
warn_unused_configs = true

[tool.ruff]
line-length = 88
target-version = "py311"
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "UP", # pyupgrade
]