name = "ai-newscast-news-crawler-worker"
main = "dist/worker.js"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat", "cots_on_external_fetch"]

[vars]
# Add environment variables here

[observability]
enabled = true

# Cron triggers removed - now managed by newscast-scheduler-worker
# Previous schedule:
# - "5 9 * * *" (09:05 - Crawl Topics)
# - "11-40 9 * * *" (09:11-09:40 - Crawl News Details)

[[r2_buckets]]
binding = "AI_NEWSCAST_BUCKET"
bucket_name = "ai-newscast"
preview_bucket_name = "ai-newscast"

[[kv_namespaces]]
binding = "AI_NEWSCAST_KV"
id = "1a002997dc124ce9a4ff5080a7e2b5e6"
preview_id = "1a002997dc124ce9a4ff5080a7e2b5e6"