name = "ai-newscast-news-crawler-worker"
main = "dist/worker.js"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat", "cots_on_external_fetch"]

[vars]
# Add environment variables here

[triggers]
crons = [
  "0 * * * *",     # Every hour at 0 minutes - topics
  "5-30 * * * *"   # Every hour at 5-30 minutes - news details
]

[[r2_buckets]]
binding = "AI_NEWSCAST_BUCKET"
bucket_name = "ai-newscast"
preview_bucket_name = "ai-newscast"

[[kv_namespaces]]
binding = "AI_NEWSCAST_KV"
id = "1a002997dc124ce9a4ff5080a7e2b5e6"
preview_id = "1a002997dc124ce9a4ff5080a7e2b5e6"