name = "ai-newscast-news-generator-worker"
main = "dist/worker.js"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat", "cots_on_external_fetch"]

[vars]
GEMINI_MODEL = "gemini-2.5-flash-lite"

[observability]
enabled = true

# Cron triggers removed - now managed by newscast-scheduler-worker
# Previous schedule:
# - "41-50 9 * * *" (09:41-09:50 - Generate News for topics 1-10)

[[r2_buckets]]
binding = "AI_NEWSCAST_BUCKET"
bucket_name = "ai-newscast"
preview_bucket_name = "ai-newscast"

[[kv_namespaces]]
binding = "AI_NEWSCAST_KV"
id = "1a002997dc124ce9a4ff5080a7e2b5e6"
preview_id = "1a002997dc124ce9a4ff5080a7e2b5e6"