name = "newscast-scheduler-worker"
main = "dist/worker.js"
compatibility_date = "2024-11-27"

[observability]
enabled = true

# KV Namespace
[[kv_namespaces]]
binding = "AI_NEWSCAST_KV"
id = "1a002997dc124ce9a4ff5080a7e2b5e6"

# R2 Bucket
[[r2_buckets]]
binding = "AI_NEWSCAST_BUCKET"
bucket_name = "ai-newscast"

# Cron Triggers (통합 스케줄 - 1개로 통합)
# 전체 파이프라인: 09:05-10:30 UTC (매분 실행, 시간 기반 작업 분기)
# - 09:05 UTC (18:05 KST): Crawl Topics
# - 09:11-09:40 UTC (18:11-18:40 KST): Crawl News Details
# - 09:41-09:50 UTC (18:41-18:50 KST): Generate News (topics 1-10)
# - 09:51-10:00 UTC (18:51-19:00 KST): Generate Script (topics 1-10)
# - 10:01-10:10 UTC (19:01-19:10 KST): Generate Audio (topics 1-10)
# - 10:11-10:20 UTC (19:11-19:20 KST): Merge Newscast (topics 1-10)
# - 10:30 UTC (19:30 KST): Complete Pipeline (검증 후 latest-newscast-id 업데이트)
[triggers]
crons = [
  "* 9-10 * * *"  # 09:00-10:59 UTC (KST 18:00-19:59) 매분 실행
]

# Service Bindings (worker 간 내부 통신)
[[services]]
binding = "NEWS_CRAWLER_WORKER"
service = "ai-newscast-news-crawler-worker"

[[services]]
binding = "NEWS_GENERATOR_WORKER"
service = "ai-newscast-news-generator-worker"

[[services]]
binding = "NEWSCAST_GENERATOR_WORKER"
service = "ai-newscast-newscast-generator-worker"
