name = "newscast-scheduler-worker"
main = "dist/worker.js"
compatibility_date = "2024-11-27"

[observability]
enabled = true

# KV Namespace
[[kv_namespaces]]
binding = "AI_NEWSCAST_KV"
id = "1a002997dc124ce9a4ff5080a7e2b5e6"

# Cron Triggers (통합 스케줄 - 1개로 통합)
# 전체 파이프라인: 09:05-10:20 (매분 실행, 시간 기반 작업 분기)
# - 09:05: Crawl Topics
# - 09:11-09:40: Crawl News Details
# - 09:41-09:50: Generate News (topics 1-10)
# - 09:51-10:00: Generate Script (topics 1-10)
# - 10:01-10:10: Generate Audio (topics 1-10)
# - 10:11-10:20: Merge Newscast (topics 1-10)
[triggers]
crons = [
  "* 9-10 * * *"  # 09:00-10:59 UTC (KST 18:00-19:59) 매분 실행
]

# Service Bindings (worker 간 내부 통신)
[[services]]
binding = "NEWS_CRAWLER_WORKER"
service = "ai-newscast-news-crawler-worker"

[[services]]
binding = "NEWS_GENERATOR_WORKER"
service = "ai-newscast-news-generator-worker"

[[services]]
binding = "NEWSCAST_GENERATOR_WORKER"
service = "ai-newscast-newscast-generator-worker"
