name = "ai-newscast-newscast-generator-worker"
main = "dist/worker.js"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]

[vars]
# Add environment variables here
# GOOGLE_GEN_AI_API_KEY will be set via secrets
AWS_LAMBDA_NEWSCAST_API_URL = "https://mjo3i4woz9.execute-api.ap-northeast-2.amazonaws.com"

[observability]
enabled = true

[triggers]
crons = [
  "1-10 10 * * *",  # Daily at 10:01-10 UTC (19:01-10 KST) - script generation
  "11-20 10 * * *"  # Test at 10:11-20 UTC (19:11-20 KST) - audio generation
]

[[r2_buckets]]
binding = "AI_NEWSCAST_BUCKET"
bucket_name = "ai-newscast"
preview_bucket_name = "ai-newscast"

[[kv_namespaces]]
binding = "AI_NEWSCAST_KV"
id = "1a002997dc124ce9a4ff5080a7e2b5e6"
preview_id = "1a002997dc124ce9a4ff5080a7e2b5e6"
