name = "ai-newscast-newscast-generator-worker"
main = "dist/worker.js"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]

[vars]
GEMINI_MODEL = "gemini-2.5-flash-lite"
AWS_LAMBDA_NEWSCAST_API_URL = "https://mjo3i4woz9.execute-api.ap-northeast-2.amazonaws.com"
TTS_DELAY_MS = "1000"

[observability]
enabled = true

# Cron triggers removed - now managed by newscast-scheduler-worker
# Previous schedule:
# - "1-10 10 * * *" (10:01-10:10 - Generate Script for topics 1-10)
# - "11-20 10 * * *" (10:11-10:20 - Generate Audio & Merge Newscast for topics 1-10)

[[r2_buckets]]
binding = "AI_NEWSCAST_BUCKET"
bucket_name = "ai-newscast"
preview_bucket_name = "ai-newscast"

[[kv_namespaces]]
binding = "AI_NEWSCAST_KV"
id = "1a002997dc124ce9a4ff5080a7e2b5e6"
preview_id = "1a002997dc124ce9a4ff5080a7e2b5e6"
